spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:${random.uuid}
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
releaser:
  git:
    org-name: spring-cloud
    release-train-bom-url: https://github.com/spring-cloud/spring-cloud-stream-starters
    documentation-url: https://github.com/spring-cloud/spring-cloud-static
    number-of-checked-milestones: 50
    update-github-milestones: true
  pom:
    branch: main
    pom-with-boot-starter-parent: spring-cloud-starter-parent/pom.xml
    this-train-bom: spring-cloud-stream-dependencies/pom.xml
    bom-version-pattern: "^(spring-cloud-.*)\\.version$"
    ignored-pom-regex:
      - "^.*\\.git/.*$"
  maven:
    build-command: "./mvnw clean install -B -Pdocs {{systemProps}}"
    deploy-command: "./mvnw deploy -DskipTests -B -Pfast,deploy {{systemProps}}"
    deploy-guides-command: "./mvnw clean verify deploy -B -Pguides,integration -pl guides {{systemProps}}"
    publish-docs-command: "./mvnw deploy -DskipTests -B -Pfast,deploy,docs {{systemProps}}"
    generate-release-train-docs-command: "bash release_train.sh --retrieveversions --version {{version}} --ghpages --auto"
  sagan:
    update-sagan: true
  meta-release:
    release-train-project-name: spring-cloud-stream-starters
    release-train-dependency-names:
      - spring-cloud-stream-dependencies
      - spring-cloud-stream-starter-build
    git-org-url: https://github.com/spring-cloud
    projects-to-skip:
      - spring-boot
      - spring-cloud-build
      - spring-cloud-function